os:
- osx
osx_image: xcode9.2
language: objective-c
sudo: required
dist: trusty

script:
  - xcodebuild -workspace CsapaTom.xcworkspace -scheme CsapaTom -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO













   
